package com.solvd.schoolschedule.dao.interfaces;

import java.util.List;

import com.solvd.schoolschedule.model.Timetable;

/**
 * Data Access Object interface for Timetable entity operations.
 * Provides CRUD operations for managing timetables in the database.
 *
 * <p>A timetable represents a complete schedule generated by the genetic algorithm.
 * Each timetable contains multiple lessons and is associated with metadata like
 * fitness score, generation number, and creation timestamp.</p>
 *
 * <p>When creating a timetable, all associated lessons are automatically saved
 * through the cascading behavior implemented in the DAO.</p>
 */
public interface ITimetableDAO {
    /**
     * Creates a new timetable in the database along with all its lessons.
     * Automatically generates a name with timestamp and saves all lessons.
     *
     * @param timetable the Timetable to insert (with all lessons)
     * @throws RuntimeException if a database error occurs
     */
    void create(Timetable timetable);

    /**
     * Retrieves a timetable by its ID, including all associated lessons.
     * Loads all lessons from the lesson table and adds them to the timetable.
     *
     * @param timetableId the unique identifier of the timetable
     * @return the Timetable object with all lessons, or null if not found
     * @throws RuntimeException if a database error occurs
     */
    Timetable getById(int timetableId);

    /**
     * Retrieves all timetables from the database, including their lessons.
     *
     * @return a list of all Timetable objects with their lessons
     * @throws RuntimeException if a database error occurs
     */
    List<Timetable> getAll();

    /**
     * Updates a timetable (currently not supported).
     * Timetables are immutable - create a new one instead of updating.
     *
     * @param timetable the Timetable to update
     * @throws UnsupportedOperationException always
     */
    void update(Timetable timetable);

    /**
     * Deletes a timetable and all its lessons from the database.
     * Uses a transaction to ensure both are deleted atomically.
     *
     * @param timetableId the ID of the timetable to delete
     * @throws RuntimeException if a database error occurs
     */
    void delete(int timetableId);
}
